sudo : required
language : java
before_install :
- curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >t.jar
- sudo java -jar t.jar init
- rm t.jar
install :
- sudo jpm install com.codacy:codacy-coverage-reporter:assembly
- mvn install
script :
- mvn clean package -DskipTests
- mvn cobertura:cobertura
- codacy-coverage-reporter -l Java --projectToken $CODACY_PROJECT_TOKEN -r target/site/cobertura/coverage.xml
